### ISSUE TITLE
Version 211.3.1 seems to be broken 

### ISSUE THREAD

**Issue by fappel** [zielu/cleansheet4idea#3]
after updating to the latest version clean sheet seems to be broken. Am I missing something? Regards Frank

![image](https://user-images.githubusercontent.com/776277/169942689-10632870-bf9e-4d4b-b60b-1b866773f0e9.png)

![image](https://user-images.githubusercontent.com/776277/169942446-a462b316-e54b-471a-871a-8a1d355ff6e9.png)

**Comment by fappel** [comment]
Reinstalling did solve the problem for me :-) Sorry for bothering... regards Frank

![image](https://user-images.githubusercontent.com/776277/169945142-d15cd13e-dc6f-44a7-8665-7edb0085b7ad.png)

**Comment by fappel** [comment]
Hm, having the same problem again with version 211.3.6. However, reinstalling the theme does not fix the problem this time. Syntax highlighting is broken as it is shown in the first screen shot in this issue

**Comment by fappel** [comment]
Ok, I could resolve it. I had to manually restore the Editor -> Color Scheme settings. Sorry again for bothering...

**Comment by zielu** [comment]
No problem :)
